CREATE TABLE IF NOT EXISTS houses (
    id SERIAL PRIMARY KEY,
    year_built INTEGER NOT NULL,
    address VARCHAR(255) NOT NULL,
    developer VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);