version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SERVER_ADDRESS=":8080"
  #     - JWT_SECRET="secret"
  #     - DB_CONNECTION="postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
  #   depends_on:
  #     - db
  #     - migrator

  # migrator:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.migrator
  #   environment:
  #     - DB_CONNECTION="postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
  #   depends_on:
  #     - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"